apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
          livenessProbe:
            httpGet:
              path: /
              port: 5050
            initialDelaySeconds: 15
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
    metallb.universe.tf/allow-shared-ip: wp
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: wordpress
  ports:
  - port: 5050
    name: http
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100